/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package idmanager;

import EntityAndMethod.Method;
import idmanagerBLL.SelectBLL;
import javax.swing.JOptionPane;

/**
 *
 * @author s7995
 */
public class SelectFrame extends javax.swing.JDialog {

    String account;
    SelectBLL bll = new SelectBLL();
    MainFrame main;
            
    /**
     * Creates new form SelectFrame
     */
    public SelectFrame() {
        initComponents();
    }
    public SelectFrame(String account, MainFrame main){
        initComponents();
        this.account = account;
        this.main = main;
        if(!account.equals("admin")){
            Author.setText(account);
            Author.setEditable(false);
        }
        buttonGroup1.add(Name);
        buttonGroup1.add(ID);
        buttonGroup1.add(Phone);
        buttonGroup1.add(Age);
        buttonGroup1.add(Birthday);
        buttonGroup1.add(Gender);
        buttonGroup1.add(Region);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Name = new javax.swing.JRadioButton();
        ID = new javax.swing.JRadioButton();
        Phone = new javax.swing.JRadioButton();
        Age = new javax.swing.JRadioButton();
        Birthday = new javax.swing.JRadioButton();
        Gender = new javax.swing.JRadioButton();
        Value = new javax.swing.JTextField();
        Author = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        yes = new javax.swing.JButton();
        no = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Region = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("查询");

        Name.setSelected(true);
        Name.setText("姓名");

        ID.setText("身份证号");

        Phone.setText("电话");

        Age.setText("年龄");

        Birthday.setText("出生日期");

        Gender.setText("性别");

        jLabel1.setText("值");

        jLabel2.setText("添加者");

        yes.setText("确定");
        yes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesActionPerformed(evt);
            }
        });

        no.setText("关闭");
        no.setToolTipText("");
        no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noActionPerformed(evt);
            }
        });

        jLabel3.setText("注：如输入年龄段");

        jLabel4.setText("格式为形如11-23；");

        jLabel5.setText("出生日期为形如20");

        jLabel6.setText("18年或2018年6月或");
        jLabel6.setToolTipText("");

        jLabel7.setText("2018年6月20日");

        Region.setText("地区");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(yes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(no))
                    .addComponent(Author)
                    .addComponent(Value)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Region)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Phone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Age)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Birthday)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Gender)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Name)
                            .addComponent(ID)
                            .addComponent(Phone)
                            .addComponent(Age)
                            .addComponent(Birthday)
                            .addComponent(Gender)
                            .addComponent(Region))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Author, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yes)
                    .addComponent(no))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noActionPerformed
        // TODO add your handling code here:
        offlineDetect();
        this.dispose();
    }//GEN-LAST:event_noActionPerformed

    private void yesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesActionPerformed
        // TODO add your handling code here:
        offlineDetect();
        String type;
        String author = Author.getText().trim();
        String value = Value.getText().trim();
        Object[][] data;
        if (value.equals("") && !author.equals("")) {    //如果添加者填了但值没有填则查找添加者添加的所有记录
            try {
                data = bll.selectByAuthor(Author.getText().trim());
                JOptionPane.showMessageDialog(this, "查询成功", "成功", JOptionPane.INFORMATION_MESSAGE);
                this.main.setTableModel(data);
                this.dispose();
                return;
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "查询错误，错误信息：" + ex, "错误", JOptionPane.ERROR_MESSAGE);
            }
        } else if (value.equals("")) {
            JOptionPane.showMessageDialog(this, "请填写信息", "错误", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(Name.isSelected()) type = "Name";
        else if(ID.isSelected()) type = "ID";
        else if(Phone.isSelected()) type = "Phone";
        else if(Age.isSelected()) type = "Age";
        else if(Birthday.isSelected()) type = "Birthday";
        else if(Region.isSelected()) type = "Region";
        else type = "Gender";
        try{
            data = bll.select(type, value, author, account);
            JOptionPane.showMessageDialog(this, "查询成功", "成功", JOptionPane.INFORMATION_MESSAGE);
            this.main.setTableModel(data);
            this.dispose();
        }catch(Exception ex){
             JOptionPane.showMessageDialog(this, "查询错误，错误信息：" + ex, "错误", JOptionPane.ERROR_MESSAGE);
        }
                    
    }//GEN-LAST:event_yesActionPerformed

    private void offlineDetect() {

        try {
            if (!bll.detect(account, Method.getInternetIp())) {
                JOptionPane.showMessageDialog(this, "您已经离线！", "错误", JOptionPane.ERROR_MESSAGE);
                System.exit(0);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "程序出现错误，错误信息：" + ex, "错误", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Age;
    private javax.swing.JTextField Author;
    private javax.swing.JRadioButton Birthday;
    private javax.swing.JRadioButton Gender;
    private javax.swing.JRadioButton ID;
    private javax.swing.JRadioButton Name;
    private javax.swing.JRadioButton Phone;
    private javax.swing.JRadioButton Region;
    private javax.swing.JTextField Value;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton no;
    private javax.swing.JButton yes;
    // End of variables declaration//GEN-END:variables
}
